export const REQUEST_QUERY_INVALID = "REQUEST_QUERY_INVALID";
export const REQUEST_BODY_INVALID = "REQUEST_BODY_INVALID";
export const REQUEST_METHOD_INVALID = "REQUEST_METHOD_INVALID";
export const NOT_AUTHORIZED = "NOT_AUTHORIZED";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const ITEM_NOT_FOUND = "ITEM_NOT_FOUND";
export const DUPLICATE_ITEM = "DUPLICATE_ITEM";

export type Errors = {
  readonly REQUEST_QUERY_INVALID: string;
  readonly REQUEST_BODY_INVALID: string;
  readonly REQUEST_METHOD_INVALID: string;
  readonly NOT_AUTHORIZED: string;
  readonly INTERNAL_SERVER_ERROR: string;
  readonly ITEM_NOT_FOUND: string;
  readonly DUPLICATE_ITEM: string;
};

/**
 * Errors returned by API
 */
export const errors: Errors = {
  REQUEST_QUERY_INVALID,
  REQUEST_BODY_INVALID,
  REQUEST_METHOD_INVALID,
  NOT_AUTHORIZED,
  INTERNAL_SERVER_ERROR,
  ITEM_NOT_FOUND,
  DUPLICATE_ITEM,
};
